using FluentAssertions;
using NINA.Joko.Plugin.TenMicron.Model;
using NINA.Joko.Plugin.TenMicron.ModelManagement;
using NUnit.Framework;

namespace NINA.Joko.Plugin.TenMicron.Tests.ModelManagement {

    [TestFixture]
    public class ModelBuilderPointFilterTests {

        [Test]
        public void IsPointIncludedInBuild_Generated_IsIncluded() {
            ModelBuilder.IsPointIncludedInBuild(ModelPointStateEnum.Generated).Should().BeTrue();
        }

        [TestCase(ModelPointStateEnum.UpNext)]
        [TestCase(ModelPointStateEnum.Exposing)]
        [TestCase(ModelPointStateEnum.Processing)]
        [TestCase(ModelPointStateEnum.AddedToModel)]
        [TestCase(ModelPointStateEnum.Failed)]
        [TestCase(ModelPointStateEnum.FailedRMS)]
        public void IsPointIncludedInBuild_MidBuildStates_AreIncluded(ModelPointStateEnum state) {
            // Points cycle through these states during a build. A rebuild from existing points
            // (retries, high-RMS re-adds) must keep them in ValidPoints.
            ModelBuilder.IsPointIncludedInBuild(state).Should().BeTrue();
        }

        [TestCase(ModelPointStateEnum.BelowHorizon)]
        [TestCase(ModelPointStateEnum.OutsideAltitudeBounds)]
        [TestCase(ModelPointStateEnum.OutsideAzimuthBounds)]
        [TestCase(ModelPointStateEnum.CloseToMeridian)]
        public void IsPointIncludedInBuild_GenerationTimeExclusions_AreExcluded(ModelPointStateEnum state) {
            // Regression: CloseToMeridian points were let through, then reset to Generated by
            // PreStep1_ClearState, so a 25-star request produced a 26-star model.
            ModelBuilder.IsPointIncludedInBuild(state).Should().BeFalse();
        }
    }
}
